// +build deluxe

// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Binance.proto

package binance

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Transaction struct {
	// int64 SIZE-OF-ENCODED      // varint encoded length of the structure after encoding
	// 0xF0625DEE                  // prefix
	Msgs                 [][]byte `protobuf:"bytes,1,rep,name=msgs,proto3" json:"msgs,omitempty"`
	Signatures           [][]byte `protobuf:"bytes,2,rep,name=signatures,proto3" json:"signatures,omitempty"`
	Memo                 string   `protobuf:"bytes,3,opt,name=memo,proto3" json:"memo,omitempty"`
	Source               int64    `protobuf:"varint,4,opt,name=source,proto3" json:"source,omitempty"`
	Data                 []byte   `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f7fcda3ac4f3e4a, []int{0}
}

func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetMsgs() [][]byte {
	if m != nil {
		return m.Msgs
	}
	return nil
}

func (m *Transaction) GetSignatures() [][]byte {
	if m != nil {
		return m.Signatures
	}
	return nil
}

func (m *Transaction) GetMemo() string {
	if m != nil {
		return m.Memo
	}
	return ""
}

func (m *Transaction) GetSource() int64 {
	if m != nil {
		return m.Source
	}
	return 0
}

func (m *Transaction) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Signature struct {
	PubKey               []byte   `protobuf:"bytes,1,opt,name=pub_key,json=pubKey,proto3" json:"pub_key,omitempty"`
	Signature            []byte   `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	AccountNumber        int64    `protobuf:"varint,3,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	Sequence             int64    `protobuf:"varint,4,opt,name=sequence,proto3" json:"sequence,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Signature) Reset()         { *m = Signature{} }
func (m *Signature) String() string { return proto.CompactTextString(m) }
func (*Signature) ProtoMessage()    {}
func (*Signature) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f7fcda3ac4f3e4a, []int{1}
}

func (m *Signature) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Signature.Unmarshal(m, b)
}
func (m *Signature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Signature.Marshal(b, m, deterministic)
}
func (m *Signature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Signature.Merge(m, src)
}
func (m *Signature) XXX_Size() int {
	return xxx_messageInfo_Signature.Size(m)
}
func (m *Signature) XXX_DiscardUnknown() {
	xxx_messageInfo_Signature.DiscardUnknown(m)
}

var xxx_messageInfo_Signature proto.InternalMessageInfo

func (m *Signature) GetPubKey() []byte {
	if m != nil {
		return m.PubKey
	}
	return nil
}

func (m *Signature) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *Signature) GetAccountNumber() int64 {
	if m != nil {
		return m.AccountNumber
	}
	return 0
}

func (m *Signature) GetSequence() int64 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

type Signature_PubKey struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Signature_PubKey) Reset()         { *m = Signature_PubKey{} }
func (m *Signature_PubKey) String() string { return proto.CompactTextString(m) }
func (*Signature_PubKey) ProtoMessage()    {}
func (*Signature_PubKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f7fcda3ac4f3e4a, []int{1, 0}
}

func (m *Signature_PubKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Signature_PubKey.Unmarshal(m, b)
}
func (m *Signature_PubKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Signature_PubKey.Marshal(b, m, deterministic)
}
func (m *Signature_PubKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Signature_PubKey.Merge(m, src)
}
func (m *Signature_PubKey) XXX_Size() int {
	return xxx_messageInfo_Signature_PubKey.Size(m)
}
func (m *Signature_PubKey) XXX_DiscardUnknown() {
	xxx_messageInfo_Signature_PubKey.DiscardUnknown(m)
}

var xxx_messageInfo_Signature_PubKey proto.InternalMessageInfo

type TradeOrder struct {
	// 0xCE6DC043           // prefix
	Sender               []byte   `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Symbol               string   `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Ordertype            int64    `protobuf:"varint,4,opt,name=ordertype,proto3" json:"ordertype,omitempty"`
	Side                 int64    `protobuf:"varint,5,opt,name=side,proto3" json:"side,omitempty"`
	Price                int64    `protobuf:"varint,6,opt,name=price,proto3" json:"price,omitempty"`
	Quantity             int64    `protobuf:"varint,7,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Timeinforce          int64    `protobuf:"varint,8,opt,name=timeinforce,proto3" json:"timeinforce,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TradeOrder) Reset()         { *m = TradeOrder{} }
func (m *TradeOrder) String() string { return proto.CompactTextString(m) }
func (*TradeOrder) ProtoMessage()    {}
func (*TradeOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f7fcda3ac4f3e4a, []int{2}
}

func (m *TradeOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TradeOrder.Unmarshal(m, b)
}
func (m *TradeOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TradeOrder.Marshal(b, m, deterministic)
}
func (m *TradeOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TradeOrder.Merge(m, src)
}
func (m *TradeOrder) XXX_Size() int {
	return xxx_messageInfo_TradeOrder.Size(m)
}
func (m *TradeOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_TradeOrder.DiscardUnknown(m)
}

var xxx_messageInfo_TradeOrder proto.InternalMessageInfo

func (m *TradeOrder) GetSender() []byte {
	if m != nil {
		return m.Sender
	}
	return nil
}

func (m *TradeOrder) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *TradeOrder) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *TradeOrder) GetOrdertype() int64 {
	if m != nil {
		return m.Ordertype
	}
	return 0
}

func (m *TradeOrder) GetSide() int64 {
	if m != nil {
		return m.Side
	}
	return 0
}

func (m *TradeOrder) GetPrice() int64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *TradeOrder) GetQuantity() int64 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *TradeOrder) GetTimeinforce() int64 {
	if m != nil {
		return m.Timeinforce
	}
	return 0
}

type CancelTradeOrder struct {
	// 0x166E681B      // prefix
	Sender               []byte   `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Symbol               string   `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Refid                string   `protobuf:"bytes,3,opt,name=refid,proto3" json:"refid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelTradeOrder) Reset()         { *m = CancelTradeOrder{} }
func (m *CancelTradeOrder) String() string { return proto.CompactTextString(m) }
func (*CancelTradeOrder) ProtoMessage()    {}
func (*CancelTradeOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f7fcda3ac4f3e4a, []int{3}
}

func (m *CancelTradeOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelTradeOrder.Unmarshal(m, b)
}
func (m *CancelTradeOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelTradeOrder.Marshal(b, m, deterministic)
}
func (m *CancelTradeOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelTradeOrder.Merge(m, src)
}
func (m *CancelTradeOrder) XXX_Size() int {
	return xxx_messageInfo_CancelTradeOrder.Size(m)
}
func (m *CancelTradeOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelTradeOrder.DiscardUnknown(m)
}

var xxx_messageInfo_CancelTradeOrder proto.InternalMessageInfo

func (m *CancelTradeOrder) GetSender() []byte {
	if m != nil {
		return m.Sender
	}
	return nil
}

func (m *CancelTradeOrder) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *CancelTradeOrder) GetRefid() string {
	if m != nil {
		return m.Refid
	}
	return ""
}

type SendOrder struct {
	Inputs               []*SendOrder_Input  `protobuf:"bytes,1,rep,name=inputs,proto3" json:"inputs,omitempty"`
	Outputs              []*SendOrder_Output `protobuf:"bytes,2,rep,name=outputs,proto3" json:"outputs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *SendOrder) Reset()         { *m = SendOrder{} }
func (m *SendOrder) String() string { return proto.CompactTextString(m) }
func (*SendOrder) ProtoMessage()    {}
func (*SendOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f7fcda3ac4f3e4a, []int{4}
}

func (m *SendOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendOrder.Unmarshal(m, b)
}
func (m *SendOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendOrder.Marshal(b, m, deterministic)
}
func (m *SendOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendOrder.Merge(m, src)
}
func (m *SendOrder) XXX_Size() int {
	return xxx_messageInfo_SendOrder.Size(m)
}
func (m *SendOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_SendOrder.DiscardUnknown(m)
}

var xxx_messageInfo_SendOrder proto.InternalMessageInfo

func (m *SendOrder) GetInputs() []*SendOrder_Input {
	if m != nil {
		return m.Inputs
	}
	return nil
}

func (m *SendOrder) GetOutputs() []*SendOrder_Output {
	if m != nil {
		return m.Outputs
	}
	return nil
}

// 0x2A2C87FA
type SendOrder_Token struct {
	Denom                string   `protobuf:"bytes,1,opt,name=denom,proto3" json:"denom,omitempty"`
	Amount               int64    `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendOrder_Token) Reset()         { *m = SendOrder_Token{} }
func (m *SendOrder_Token) String() string { return proto.CompactTextString(m) }
func (*SendOrder_Token) ProtoMessage()    {}
func (*SendOrder_Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f7fcda3ac4f3e4a, []int{4, 0}
}

func (m *SendOrder_Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendOrder_Token.Unmarshal(m, b)
}
func (m *SendOrder_Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendOrder_Token.Marshal(b, m, deterministic)
}
func (m *SendOrder_Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendOrder_Token.Merge(m, src)
}
func (m *SendOrder_Token) XXX_Size() int {
	return xxx_messageInfo_SendOrder_Token.Size(m)
}
func (m *SendOrder_Token) XXX_DiscardUnknown() {
	xxx_messageInfo_SendOrder_Token.DiscardUnknown(m)
}

var xxx_messageInfo_SendOrder_Token proto.InternalMessageInfo

func (m *SendOrder_Token) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func (m *SendOrder_Token) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type SendOrder_Input struct {
	Address              []byte             `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Coins                []*SendOrder_Token `protobuf:"bytes,2,rep,name=coins,proto3" json:"coins,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *SendOrder_Input) Reset()         { *m = SendOrder_Input{} }
func (m *SendOrder_Input) String() string { return proto.CompactTextString(m) }
func (*SendOrder_Input) ProtoMessage()    {}
func (*SendOrder_Input) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f7fcda3ac4f3e4a, []int{4, 1}
}

func (m *SendOrder_Input) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendOrder_Input.Unmarshal(m, b)
}
func (m *SendOrder_Input) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendOrder_Input.Marshal(b, m, deterministic)
}
func (m *SendOrder_Input) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendOrder_Input.Merge(m, src)
}
func (m *SendOrder_Input) XXX_Size() int {
	return xxx_messageInfo_SendOrder_Input.Size(m)
}
func (m *SendOrder_Input) XXX_DiscardUnknown() {
	xxx_messageInfo_SendOrder_Input.DiscardUnknown(m)
}

var xxx_messageInfo_SendOrder_Input proto.InternalMessageInfo

func (m *SendOrder_Input) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *SendOrder_Input) GetCoins() []*SendOrder_Token {
	if m != nil {
		return m.Coins
	}
	return nil
}

type SendOrder_Output struct {
	Address              []byte             `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Coins                []*SendOrder_Token `protobuf:"bytes,2,rep,name=coins,proto3" json:"coins,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *SendOrder_Output) Reset()         { *m = SendOrder_Output{} }
func (m *SendOrder_Output) String() string { return proto.CompactTextString(m) }
func (*SendOrder_Output) ProtoMessage()    {}
func (*SendOrder_Output) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f7fcda3ac4f3e4a, []int{4, 2}
}

func (m *SendOrder_Output) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendOrder_Output.Unmarshal(m, b)
}
func (m *SendOrder_Output) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendOrder_Output.Marshal(b, m, deterministic)
}
func (m *SendOrder_Output) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendOrder_Output.Merge(m, src)
}
func (m *SendOrder_Output) XXX_Size() int {
	return xxx_messageInfo_SendOrder_Output.Size(m)
}
func (m *SendOrder_Output) XXX_DiscardUnknown() {
	xxx_messageInfo_SendOrder_Output.DiscardUnknown(m)
}

var xxx_messageInfo_SendOrder_Output proto.InternalMessageInfo

func (m *SendOrder_Output) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *SendOrder_Output) GetCoins() []*SendOrder_Token {
	if m != nil {
		return m.Coins
	}
	return nil
}

type TokenFreezeOrder struct {
	// 0xE774B32D      // prefix
	From                 []byte   `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	Symbol               string   `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Amount               int64    `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenFreezeOrder) Reset()         { *m = TokenFreezeOrder{} }
func (m *TokenFreezeOrder) String() string { return proto.CompactTextString(m) }
func (*TokenFreezeOrder) ProtoMessage()    {}
func (*TokenFreezeOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f7fcda3ac4f3e4a, []int{5}
}

func (m *TokenFreezeOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenFreezeOrder.Unmarshal(m, b)
}
func (m *TokenFreezeOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenFreezeOrder.Marshal(b, m, deterministic)
}
func (m *TokenFreezeOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenFreezeOrder.Merge(m, src)
}
func (m *TokenFreezeOrder) XXX_Size() int {
	return xxx_messageInfo_TokenFreezeOrder.Size(m)
}
func (m *TokenFreezeOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenFreezeOrder.DiscardUnknown(m)
}

var xxx_messageInfo_TokenFreezeOrder proto.InternalMessageInfo

func (m *TokenFreezeOrder) GetFrom() []byte {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *TokenFreezeOrder) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *TokenFreezeOrder) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type TokenUnfreezeOrder struct {
	// 0x6515FF0D      // prefix
	From                 []byte   `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	Symbol               string   `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Amount               int64    `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenUnfreezeOrder) Reset()         { *m = TokenUnfreezeOrder{} }
func (m *TokenUnfreezeOrder) String() string { return proto.CompactTextString(m) }
func (*TokenUnfreezeOrder) ProtoMessage()    {}
func (*TokenUnfreezeOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f7fcda3ac4f3e4a, []int{6}
}

func (m *TokenUnfreezeOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenUnfreezeOrder.Unmarshal(m, b)
}
func (m *TokenUnfreezeOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenUnfreezeOrder.Marshal(b, m, deterministic)
}
func (m *TokenUnfreezeOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenUnfreezeOrder.Merge(m, src)
}
func (m *TokenUnfreezeOrder) XXX_Size() int {
	return xxx_messageInfo_TokenUnfreezeOrder.Size(m)
}
func (m *TokenUnfreezeOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenUnfreezeOrder.DiscardUnknown(m)
}

var xxx_messageInfo_TokenUnfreezeOrder proto.InternalMessageInfo

func (m *TokenUnfreezeOrder) GetFrom() []byte {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *TokenUnfreezeOrder) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *TokenUnfreezeOrder) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

// Input data necessary to create a signed order.
type SigningInput struct {
	ChainId       string `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	AccountNumber int64  `protobuf:"varint,2,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	Sequence      int64  `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Source        int64  `protobuf:"varint,4,opt,name=source,proto3" json:"source,omitempty"`
	Memo          string `protobuf:"bytes,5,opt,name=memo,proto3" json:"memo,omitempty"`
	PrivateKey    []byte `protobuf:"bytes,6,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	// Types that are valid to be assigned to OrderOneof:
	//	*SigningInput_TradeOrder
	//	*SigningInput_CancelTradeOrder
	//	*SigningInput_SendOrder
	//	*SigningInput_FreezeOrder
	//	*SigningInput_UnfreezeOrder
	OrderOneof           isSigningInput_OrderOneof `protobuf_oneof:"order_oneof"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *SigningInput) Reset()         { *m = SigningInput{} }
func (m *SigningInput) String() string { return proto.CompactTextString(m) }
func (*SigningInput) ProtoMessage()    {}
func (*SigningInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f7fcda3ac4f3e4a, []int{7}
}

func (m *SigningInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SigningInput.Unmarshal(m, b)
}
func (m *SigningInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SigningInput.Marshal(b, m, deterministic)
}
func (m *SigningInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SigningInput.Merge(m, src)
}
func (m *SigningInput) XXX_Size() int {
	return xxx_messageInfo_SigningInput.Size(m)
}
func (m *SigningInput) XXX_DiscardUnknown() {
	xxx_messageInfo_SigningInput.DiscardUnknown(m)
}

var xxx_messageInfo_SigningInput proto.InternalMessageInfo

func (m *SigningInput) GetChainId() string {
	if m != nil {
		return m.ChainId
	}
	return ""
}

func (m *SigningInput) GetAccountNumber() int64 {
	if m != nil {
		return m.AccountNumber
	}
	return 0
}

func (m *SigningInput) GetSequence() int64 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func (m *SigningInput) GetSource() int64 {
	if m != nil {
		return m.Source
	}
	return 0
}

func (m *SigningInput) GetMemo() string {
	if m != nil {
		return m.Memo
	}
	return ""
}

func (m *SigningInput) GetPrivateKey() []byte {
	if m != nil {
		return m.PrivateKey
	}
	return nil
}

type isSigningInput_OrderOneof interface {
	isSigningInput_OrderOneof()
}

type SigningInput_TradeOrder struct {
	TradeOrder *TradeOrder `protobuf:"bytes,8,opt,name=trade_order,json=tradeOrder,proto3,oneof"`
}

type SigningInput_CancelTradeOrder struct {
	CancelTradeOrder *CancelTradeOrder `protobuf:"bytes,9,opt,name=cancel_trade_order,json=cancelTradeOrder,proto3,oneof"`
}

type SigningInput_SendOrder struct {
	SendOrder *SendOrder `protobuf:"bytes,10,opt,name=send_order,json=sendOrder,proto3,oneof"`
}

type SigningInput_FreezeOrder struct {
	FreezeOrder *TokenFreezeOrder `protobuf:"bytes,11,opt,name=freeze_order,json=freezeOrder,proto3,oneof"`
}

type SigningInput_UnfreezeOrder struct {
	UnfreezeOrder *TokenUnfreezeOrder `protobuf:"bytes,12,opt,name=unfreeze_order,json=unfreezeOrder,proto3,oneof"`
}

func (*SigningInput_TradeOrder) isSigningInput_OrderOneof() {}

func (*SigningInput_CancelTradeOrder) isSigningInput_OrderOneof() {}

func (*SigningInput_SendOrder) isSigningInput_OrderOneof() {}

func (*SigningInput_FreezeOrder) isSigningInput_OrderOneof() {}

func (*SigningInput_UnfreezeOrder) isSigningInput_OrderOneof() {}

func (m *SigningInput) GetOrderOneof() isSigningInput_OrderOneof {
	if m != nil {
		return m.OrderOneof
	}
	return nil
}

func (m *SigningInput) GetTradeOrder() *TradeOrder {
	if x, ok := m.GetOrderOneof().(*SigningInput_TradeOrder); ok {
		return x.TradeOrder
	}
	return nil
}

func (m *SigningInput) GetCancelTradeOrder() *CancelTradeOrder {
	if x, ok := m.GetOrderOneof().(*SigningInput_CancelTradeOrder); ok {
		return x.CancelTradeOrder
	}
	return nil
}

func (m *SigningInput) GetSendOrder() *SendOrder {
	if x, ok := m.GetOrderOneof().(*SigningInput_SendOrder); ok {
		return x.SendOrder
	}
	return nil
}

func (m *SigningInput) GetFreezeOrder() *TokenFreezeOrder {
	if x, ok := m.GetOrderOneof().(*SigningInput_FreezeOrder); ok {
		return x.FreezeOrder
	}
	return nil
}

func (m *SigningInput) GetUnfreezeOrder() *TokenUnfreezeOrder {
	if x, ok := m.GetOrderOneof().(*SigningInput_UnfreezeOrder); ok {
		return x.UnfreezeOrder
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*SigningInput) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*SigningInput_TradeOrder)(nil),
		(*SigningInput_CancelTradeOrder)(nil),
		(*SigningInput_SendOrder)(nil),
		(*SigningInput_FreezeOrder)(nil),
		(*SigningInput_UnfreezeOrder)(nil),
	}
}

// Transaction signing output.
type SigningOutput struct {
	// Signed and encoded transaction bytes.
	Encoded              []byte   `protobuf:"bytes,1,opt,name=encoded,proto3" json:"encoded,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SigningOutput) Reset()         { *m = SigningOutput{} }
func (m *SigningOutput) String() string { return proto.CompactTextString(m) }
func (*SigningOutput) ProtoMessage()    {}
func (*SigningOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f7fcda3ac4f3e4a, []int{8}
}

func (m *SigningOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SigningOutput.Unmarshal(m, b)
}
func (m *SigningOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SigningOutput.Marshal(b, m, deterministic)
}
func (m *SigningOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SigningOutput.Merge(m, src)
}
func (m *SigningOutput) XXX_Size() int {
	return xxx_messageInfo_SigningOutput.Size(m)
}
func (m *SigningOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_SigningOutput.DiscardUnknown(m)
}

var xxx_messageInfo_SigningOutput proto.InternalMessageInfo

func (m *SigningOutput) GetEncoded() []byte {
	if m != nil {
		return m.Encoded
	}
	return nil
}

func init() {
	proto.RegisterType((*Transaction)(nil), "pb.Transaction")
	proto.RegisterType((*Signature)(nil), "pb.Signature")
	proto.RegisterType((*Signature_PubKey)(nil), "pb.Signature.PubKey")
	proto.RegisterType((*TradeOrder)(nil), "pb.TradeOrder")
	proto.RegisterType((*CancelTradeOrder)(nil), "pb.CancelTradeOrder")
	proto.RegisterType((*SendOrder)(nil), "pb.SendOrder")
	proto.RegisterType((*SendOrder_Token)(nil), "pb.SendOrder.Token")
	proto.RegisterType((*SendOrder_Input)(nil), "pb.SendOrder.Input")
	proto.RegisterType((*SendOrder_Output)(nil), "pb.SendOrder.Output")
	proto.RegisterType((*TokenFreezeOrder)(nil), "pb.TokenFreezeOrder")
	proto.RegisterType((*TokenUnfreezeOrder)(nil), "pb.TokenUnfreezeOrder")
	proto.RegisterType((*SigningInput)(nil), "pb.SigningInput")
	proto.RegisterType((*SigningOutput)(nil), "pb.SigningOutput")
}

func init() { proto.RegisterFile("Binance.proto", fileDescriptor_8f7fcda3ac4f3e4a) }

var fileDescriptor_8f7fcda3ac4f3e4a = []byte{
	// 734 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0xcd, 0x6e, 0xe3, 0x36,
	0x10, 0xb6, 0xa4, 0x58, 0xb6, 0x46, 0xb6, 0x11, 0xb0, 0x69, 0xa2, 0x1a, 0x45, 0x6b, 0x08, 0x28,
	0x90, 0xa0, 0x80, 0x80, 0xa6, 0xe8, 0xa1, 0xa7, 0x02, 0x69, 0x51, 0x38, 0xe8, 0x4f, 0x0a, 0x26,
	0x5d, 0xe4, 0x66, 0xc8, 0x22, 0x9d, 0xe5, 0xc6, 0x26, 0x15, 0x4a, 0xda, 0x85, 0xf7, 0xb6, 0x4f,
	0xb0, 0x2f, 0xb4, 0x4f, 0xb1, 0xef, 0xb1, 0xef, 0xb0, 0xe0, 0x88, 0xb2, 0x6c, 0x63, 0xff, 0x0e,
	0x39, 0x89, 0xdf, 0x70, 0x66, 0xf8, 0x0d, 0x67, 0x3e, 0x0a, 0x86, 0x17, 0x42, 0xa6, 0x32, 0xe3,
	0x49, 0xae, 0x55, 0xa9, 0x88, 0x9b, 0xcf, 0xe3, 0x57, 0x0e, 0x84, 0x37, 0x3a, 0x95, 0x45, 0x9a,
	0x95, 0x42, 0x49, 0x42, 0xe0, 0x60, 0x55, 0xdc, 0x15, 0x91, 0x33, 0xf1, 0x4e, 0x07, 0x14, 0xd7,
	0xe4, 0x3b, 0x80, 0x42, 0xdc, 0xc9, 0xb4, 0xac, 0x34, 0x2f, 0x22, 0x17, 0x77, 0xb6, 0x2c, 0x18,
	0xc3, 0x57, 0x2a, 0xf2, 0x26, 0xce, 0x69, 0x40, 0x71, 0x4d, 0x8e, 0xc1, 0x2f, 0x54, 0xa5, 0x33,
	0x1e, 0x1d, 0x4c, 0x9c, 0x53, 0x8f, 0x5a, 0x64, 0x7c, 0x59, 0x5a, 0xa6, 0x51, 0x77, 0xe2, 0x98,
	0xfc, 0x66, 0x1d, 0xbf, 0x76, 0x20, 0xb8, 0x6e, 0xd2, 0x91, 0x13, 0xe8, 0xe5, 0xd5, 0x7c, 0x76,
	0xcf, 0xd7, 0x91, 0x83, 0x4e, 0x7e, 0x5e, 0xcd, 0xff, 0xe2, 0x6b, 0xf2, 0x2d, 0x04, 0x9b, 0x43,
	0x23, 0x17, 0xb7, 0x5a, 0x03, 0xf9, 0x01, 0x46, 0x69, 0x96, 0xa9, 0x4a, 0x96, 0x33, 0x59, 0xad,
	0xe6, 0x5c, 0x23, 0x1d, 0x8f, 0x0e, 0xad, 0xf5, 0x5f, 0x34, 0x92, 0x31, 0xf4, 0x0b, 0xfe, 0x50,
	0x71, 0xb9, 0x61, 0xb6, 0xc1, 0xe3, 0x3e, 0xf8, 0xff, 0xe1, 0x51, 0xf1, 0x5b, 0x07, 0xe0, 0x46,
	0xa7, 0x8c, 0x5f, 0x69, 0xc6, 0x35, 0x16, 0xc3, 0x25, 0xe3, 0xba, 0x61, 0x54, 0x23, 0x32, 0x02,
	0x57, 0x30, 0xa4, 0x12, 0x50, 0x57, 0x30, 0xf4, 0x5b, 0xaf, 0xe6, 0x6a, 0x69, 0xaf, 0xc2, 0x22,
	0xc3, 0x5c, 0x99, 0x44, 0xe5, 0x3a, 0x6f, 0x4e, 0x6d, 0x0d, 0xe6, 0x4a, 0x0a, 0xc1, 0x38, 0x5e,
	0x89, 0x47, 0x71, 0x4d, 0x8e, 0xa0, 0x9b, 0x6b, 0x91, 0xf1, 0xc8, 0x47, 0x63, 0x0d, 0x0c, 0xf9,
	0x87, 0x2a, 0x95, 0xa5, 0x28, 0xd7, 0x51, 0xaf, 0x26, 0xdf, 0x60, 0x32, 0x81, 0xb0, 0x14, 0x2b,
	0x2e, 0xe4, 0x42, 0x99, 0x5b, 0xef, 0xe3, 0xf6, 0xb6, 0x29, 0xbe, 0x85, 0xc3, 0xdf, 0x4d, 0xf7,
	0x97, 0x5f, 0x50, 0x59, 0x5b, 0x89, 0xbb, 0x53, 0xc9, 0x11, 0x74, 0x35, 0x5f, 0x08, 0x66, 0x0b,
	0xac, 0x41, 0xfc, 0xc6, 0x85, 0xe0, 0x9a, 0x4b, 0x56, 0xe7, 0xfc, 0x11, 0x7c, 0x21, 0xf3, 0xaa,
	0xac, 0x87, 0x28, 0x3c, 0xff, 0x2a, 0xc9, 0xe7, 0xc9, 0x66, 0x3b, 0xb9, 0x34, 0x7b, 0xd4, 0xba,
	0x90, 0x04, 0x7a, 0xaa, 0x2a, 0xd1, 0xdb, 0x45, 0xef, 0xa3, 0x5d, 0xef, 0x2b, 0xdc, 0xa4, 0x8d,
	0xd3, 0xf8, 0x17, 0xe8, 0xde, 0xa8, 0x7b, 0x2e, 0x0d, 0x13, 0xc6, 0xa5, 0x5a, 0x21, 0xf1, 0x80,
	0xd6, 0xc0, 0xf0, 0x4e, 0x57, 0xa6, 0xdd, 0xc8, 0xdb, 0xa3, 0x16, 0x8d, 0xff, 0x86, 0x2e, 0x9e,
	0x4b, 0x22, 0xe8, 0xa5, 0x8c, 0x69, 0x5e, 0x14, 0xb6, 0xe2, 0x06, 0x92, 0x33, 0xe8, 0x66, 0x4a,
	0xc8, 0x86, 0xc7, 0x1e, 0x6b, 0x3c, 0x94, 0xd6, 0x1e, 0xe3, 0x7f, 0xc0, 0xaf, 0x79, 0x3d, 0x4a,
	0xba, 0xf8, 0x09, 0x1c, 0x22, 0xfe, 0x53, 0x73, 0xfe, 0xd2, 0x36, 0x86, 0xc0, 0xc1, 0x42, 0xdb,
	0xea, 0x06, 0x14, 0xd7, 0x1f, 0x6d, 0x4a, 0x5b, 0xb4, 0xb7, 0x5d, 0x74, 0x7c, 0x0b, 0x04, 0xf3,
	0xfe, 0x2f, 0x17, 0x8f, 0x9c, 0xf9, 0x9d, 0x07, 0x03, 0xa3, 0x58, 0x21, 0xef, 0xea, 0x6b, 0xfd,
	0x06, 0xfa, 0xd9, 0xd3, 0x54, 0xc8, 0x99, 0x60, 0xb6, 0x21, 0x3d, 0xc4, 0x97, 0xec, 0x03, 0xc2,
	0x74, 0x3f, 0x27, 0x4c, 0x6f, 0x57, 0x98, 0x9f, 0x7a, 0x4c, 0xf0, 0xe1, 0xe9, 0x6e, 0x3d, 0x3c,
	0xdf, 0x43, 0x98, 0x6b, 0xf1, 0x3c, 0x2d, 0x39, 0x3e, 0x21, 0x3e, 0x56, 0x09, 0xd6, 0x64, 0x9e,
	0x91, 0x9f, 0x20, 0x2c, 0x8d, 0x00, 0x66, 0xa8, 0x40, 0x14, 0x4a, 0x78, 0x3e, 0x32, 0xed, 0x69,
	0x75, 0x31, 0xed, 0x50, 0x28, 0x5b, 0x95, 0xfc, 0x01, 0x24, 0x43, 0xe5, 0xcc, 0xb6, 0x23, 0x03,
	0x8c, 0xc4, 0x79, 0xdd, 0xd7, 0xd5, 0xb4, 0x43, 0x0f, 0xb3, 0x7d, 0xad, 0x25, 0x00, 0x46, 0x5d,
	0x36, 0x1a, 0x30, 0x7a, 0xb8, 0x33, 0x16, 0xd3, 0x0e, 0x0d, 0x8a, 0x8d, 0x8e, 0x7e, 0x85, 0x41,
	0xdd, 0x37, 0x1b, 0x11, 0xb6, 0xe7, 0xed, 0x8f, 0xcb, 0xb4, 0x43, 0xc3, 0xed, 0x1e, 0xff, 0x06,
	0xa3, 0x4a, 0xee, 0x04, 0x0f, 0x30, 0xf8, 0x78, 0x13, 0xbc, 0x33, 0x13, 0xd3, 0x0e, 0x1d, 0x56,
	0xdb, 0x86, 0x8b, 0x21, 0x84, 0x18, 0x37, 0x53, 0x92, 0xab, 0x45, 0x7c, 0x06, 0x43, 0xdb, 0xee,
	0x76, 0xee, 0xb9, 0xcc, 0x14, 0xe3, 0xac, 0x99, 0x7b, 0x0b, 0x2f, 0x4e, 0xe0, 0xeb, 0x17, 0xe9,
	0x72, 0xc9, 0xcb, 0x24, 0x53, 0x9a, 0x27, 0xcf, 0xa4, 0xa8, 0xff, 0x36, 0x73, 0x1f, 0x3f, 0x3f,
	0xbf, 0x0f, 0x00, 0x00, 0xff, 0xff, 0xf7, 0xc6, 0xb4, 0x1b, 0x85, 0x06, 0x00, 0x00,
}
